In [8]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [9]:
cl_df  = pd.read_csv('../../data/cl_match_links_21_22.csv')
cl_df

     match match_day                                        live_ticker
0      NaN  09/14/21  https://www.goal.com/en/match/barcelona-vs-bay...
1      NaN  09/14/21  https://www.goal.com/en/match/dynamo-kyiv-vs-b...
2      NaN  09/14/21  https://www.goal.com/en/match/young-boys-vs-ma...
3      NaN  09/14/21  https://www.goal.com/en/match/villarreal-vs-at...
4      NaN  09/14/21  https://www.goal.com/en/match/sevilla-vs-salzb...
..     ...       ...                                                ...
120    NaN  04/26/22  https://www.goal.com/en/match/manchester-city-...
121    NaN  04/27/22  https://www.goal.com/en/match/liverpool-vs-vil...
122    NaN  05/03/22  https://www.goal.com/en/match/villarreal-vs-li...
123    NaN  05/04/22  https://www.goal.com/en/match/real-madrid-vs-m...
124    NaN  05/28/22  https://www.goal.com/en/match/liverpool-vs-rea...

[125 rows x 3 columns]

In [10]:
def get_match(ticker_link):
    match_words = ticker_link.split('/')[5].split('-')
    for i in range(len(match_words)):
        if i != 1:
            match_words[i] = match_words[i].capitalize()
    
    return " ".join(match_words)

In [11]:
cl_df['match'] = cl_df['live_ticker'].apply(get_match)
cl_df

,match,match_day,live_ticker
0,Barcelona vs Bayern Muenchen,09/14/21,https://www.goal.com/en/match/barcelona-vs-bay...
1,Dynamo kyiv Vs Benfica,09/14/21,https://www.goal.com/en/match/dynamo-kyiv-vs-b...
2,Young boys Vs Manchester United,09/14/21,https://www.goal.com/en/match/young-boys-vs-ma...
3,Villarreal vs Atalanta,09/14/21,https://www.goal.com/en/match/villarreal-vs-at...
4,Sevilla vs Salzburg,09/14/21,https://www.goal.com/en/match/sevilla-vs-salzb...
...,...,...,...
120,Manchester city Vs Real Madrid,04/26/22,https://www.goal.com/en/match/manchester-city-...
121,Liverpool vs Villarreal,04/27/22,https://www.goal.com/en/match/liverpool-vs-vil...
122,Villarreal vs Liverpool,05/03/22,https://www.goal.com/en/match/villarreal-vs-li...
123,Real madrid Vs Manchester City,05/04/22,https://www.goal.com/en/match/real-madrid-vs-m...
124,Liverpool vs Real Madrid,05/28/22,https://www.goal.com/en/match/liverpool-vs-rea...

In [12]:
cl_df.to_csv('../../data/cl_data_21_22.csv', index=False)